# Cultivating professionalism 

This chapter covers several aspects of professionalism that arise in the context of collaborative research, including: 

- Communication 

- Handling disagreement 

- Maintaining a CV 

- Responding to reviewers during the publication process

Each of these sections is written to be independent of the others, so skip around to what you need. 

## Communication 

### Speaking in the affirmative 

I have learned that collaboration benefits from speaking in the affirmative tense -- that is, speaking from the perspective of what you *can do*, *will do*, *do know/are learning*, and *are working on*. I've noticed that the pervasive mindset among graduate students is to complain, a habit which manifests itself in speaking in terms of what one can't do, won't do, don't know, don't have time for, etc. Change that narrative. You are not a victim. Moreover, you will be more pleasant to work with if you are positive. Whenever you are communicating with a collaborator (or PI, for that matter), frame your questions and comments in the affirmative. If you don't know the answer, describe what you will do to work with them towards their goal instead of enumerating the challenges in the way. 

### Responding to emails 

I've give these in bullets: 

- Respond to all work-related emails in 1-2 business days. If you are out of office, turn on automatic replies. 

- Start your emails with a greeting, and end with an appropriate closing. Use spell check. 

- If you are emailing a student/resident, always CC their advisor/mentor/PI. 

- If you are asking a series of questions, use bullet points -- this makes your question easier to read. 

- If you are responding to a series of questions, copy the text from the email with the questions and write your responses directly below, using a highlight or text color to make your answer stand out. This anchors your responses to the question, keeping the conversation in context. 

- If you are meeting with a group for the first time, have a conversation (either in-person or virtually) as an entire group. In my experience, collaborative projects that take place entirely via email exchange are prone to lapses in communication. 

## Handling disagreement

Here are some tricky situations that may arise when working in a GRA position, along with some suggestions on how to handle them. 

### The data is not organized in a way that is conducive to analysis 

If you've received data from folks with whom you did not consult before data collection, you may find that the data are 'messy' - maybe there are lots of notes in one column, or the data you want is in the column names, or the values within columns are not consistent. There are several resources to help you with [processing data in R](https://www.geeksforgeeks.org/processing-of-raw-data-to-tidy-data-in-r/) and/or [cleaning data in R](https://www.geeksforgeeks.org/data-cleaning-in-r/). The packages in the [tidyverse](https://www.tidyverse.org/packages/) have been super helpful to me for these tasks. I **highly recommend** that you write functions for your data cleaning/data processing scripts.

Before you dig into the computing, though, two more important questions are: 

  1. **Does the PI know what data you have?** It is quite possible that the PI was not directly involved in data collection. When the PI does not know what data you have, there is room for miscommunication - for example, the names of the variables in the data may not align with what the terminology that the PI is using. You may consider sending the PI a follow up email that describes the data you have (numbers of rows and columns, or a mock 'Table 1') and ask something like, "I want to confirm that I am looking at the right information as I begin to analyze your data. Is this [the description you've given] aligned with your expectations?" 
  
  2. **Does the data contain what you need to answer the PI's research question?** Related to the question above, if the PI is not familiar with the details of the data, it is possible that the data to which you have access is not adequate for addressing the research question. Again, describe the data you have and ask something like, "here is the data to which I have access; with my current understanding of your research question, I think you intend to analyze ... Is my understanding correct? If so, some additional information is needed."

### The data accidentally contain HIPPA protected information

This is one of those things that needs to be addressed early. Suppose that in your first exploration of a data set, you find that there is [HIPPA protected (identifiable) data](https://compliancy-group.com/what-is-hipaa-pii/#:~:text=What%20Kinds%20of%20Information%20Constitute,numbers%2C%20and%20bank%20account%20numbers.). **As soon as you realize you have this**, send an email to the person who shared the data with you and CC your GRA supervisor. Explain exactly what you have access to; say something like, "When I began to examine these data, I noticed that ___ information is included. This does not look like something to which I need access in order to address the research question. Please advise me on what needs to be done to de-identify these data?" 

### The PI is insistent on presenting results in a way that I believe is sub-optimal 

This is a tricky one -- talk to your supervisor about this problem and ask for advice. It may be that there is a happy medium; for example, if the PI is insistent on using p-values, it may be possible for you to convince them to present confidence intervals or some measure of effect size to the results as well. 

Also, encourage your PI to name the limitation of the analysis choices you've made. For example, if you have done a bunch of multiple tests and have not corrected for multiple comparisons, you should mention that explicitly in the methods section of your work. 


### I realized I made a mistake in my code! 

As soon as you've realized you made a mistake, sit down and take a minute to reconstruct when you made the mistake. Write down: 

  1. When you realized you made the mistake 
  2. Whose work will be impacted by this mistake
  
Once you have these things, consider your answer to (2). If the only people impacted by your mistake are other statisticians on your team, then email those people directly and explain what happened and what you are doing to make it right. If collaborators' (e.g., clinicians or administrators) work is impacted by your mistake, email your RA supervisor first and explain what happened. As your supervisor to help you craft an email to the impacted individuals. 

### Collaborating with other students/trainees 

If you are collaborating with other students/residents/post-docs/trainees, I recommend that you CC their advisor(s) on all important communications (sharing results, asking clarifying questions, etc.). 

### Handling inappropriate/rude emails from a faculty member

If you find yourself in the unpleasant situation where a faculty member sends an email that is rude, adversarial, or otherwise inappropriate (e.g., an investigator demands that you analyze the data according to their preferences/assumptions, even to the point of going against best practices...), I recommend that you **do not respond**. Instead, forward the email in question to your PI or other trusted senior faculty member and simply ask something like, 'just want you to know I received this today -- would you please help me handle this?'. In my experience as a student, I'd say you're better off having a senior faculty member advocate for you than to try and advocate for yourself. 

## Maintaining a CV

A curriculum vitae (CV) is not something you do once. It is something that requires constant maintenance. The tool I've found helpful for both 1) maintaining a CV that both looks professional and 2) is simple to update is the [vitae](https://pkg.mitchelloharawild.com/vitae/) package. The package site has a detailed README file with links to videos on how to set this up. I try to update my CV each time another publication is released. 

## Responding to reviewers {#point-to-point}

One more aspect of professionalism that is a part of many research jobs is publishing in academic journals. When you submit a manuscript for publication, the draft you submit is given to peer-reviewers. These reviewers offer anonymous feedback to critique your work. Knowing how to respond to these reviewers is an integral part of the writing process. [My research supervisor](https://scholar.google.com/citations?user=flqLOJIAAAAJ&hl=en&oi=ao) taught me to use the [point-to-point](https://www.nature.com/documents/Effective_Response_To_Reviewers-1.pdf) method for responding to reviewers. Templates for point-to-point response are available [here](https://onlinelibrary.wiley.com/pb-assets/assets/13989995/Point-by-point%20response-24-January%202019_CA%20approved-1549540165760.docx) and [here](https://apastyle.apa.org/style-grammar-guidelines/research-publication/sample-response-reviewers.pdf) --- check out these templates to get an idea of how to write your responses. 

