# Power and sample size calculations 

Power and sample size calculations are a common request for a GRA. In order to estimate the power or calculate the necessary sample size, you will need some measure of [effect size](https://en.wikipedia.org/wiki/Effect_size). Often, the PI may not have an effect size in mind -- in this case, offer some example scenarios and gauge the PI's reaction. Examples: 

  - "If you saw that a subject being treated in group B had a 2 mm increase in the outcome, would you be impressed? Would that be a 'big' or notable change?" 
  - "How much of an impact would you need to see in order to catch you attention in an abstract? A 50% increase? Double the outcome?" 
  
Your calculations for power/sample size could be done several ways in `R`: the [`pwr`](https://cran.r-project.org/web/packages/pwr/vignettes/pwr-vignette.html) and [`pwr2`](https://cran.r-project.org/web/packages/pwr2/pwr2.pdf) packages can be a good place to start. SAS offers the `PROC POWER` procedure for doing power and sample size calculations. I have often used both `R` and SAS functions for the same calculation and compared the results. Typically, SAS has much more in-depth documentation -- if you are wondering about the theoretical details for a calculation, [SAS documentation](https://documentation.sas.com/doc/en/statug/15.2/statug_power_toc.htm) is a helpful resource. 
